import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js';
import {getFirestore,collection,addDoc,getDocs,doc,updateDoc,deleteDoc,query,where,Timestamp,serverTimestamp,setDoc,getDoc} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';

const db=getFirestore(initializeApp(firebaseConfig));
const cats=[['comida','Comida','🍜','GASTO'],['transporte','Transporte','🚗','GASTO'],['salidas','Salidas','✨','GASTO'],['entretenimiento','Entretenimiento','🎬','GASTO'],['compras','Compras','🛍️','GASTO'],['hogar','Hogar','⌂','GASTO'],['salud','Salud','✚','GASTO'],['estudios','Estudios','▣','GASTO'],['suscripciones','Suscripciones','↻','GASTO'],['viajes','Viajes','✈','GASTO'],['regalos','Regalos','🎁','GASTO'],['otros','Otros','•••','GASTO'],['sueldo','Sueldo','▤','INGRESO'],['pago','Pago','▤','INGRESO'],['freelance','Freelance','▤','INGRESO'],['reembolso','Reembolso','↶','INGRESO'],['otros-ingresos','Otros ingresos','＋','INGRESO']];
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(+n||0), pad=n=>String(n).padStart(2,'0');
const methods=['EFECTIVO','YAPE','PLIN','TARJETA','TRANSFERENCIA','OTRO'];
const VERSION='v1.3.1';
const S={user:localStorage.ndUser||'',route:'home',month:ym(),moves:[],budget:null,edit:null};
function today(){const d=new Date;return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function ym(){return today().slice(0,7)}function moveMonth(delta){let[y,m]=S.month.split('-').map(Number);const d=new Date(y,m-1+delta,1);S.month=`${d.getFullYear()}-${pad(d.getMonth()+1)}`;load()}
function monthName(){return new Intl.DateTimeFormat('es-PE',{month:'long',year:'numeric'}).format(new Date(`${S.month}-01T12:00:00`))}function cat(id){return cats.find(c=>c[0]===id)||['otros','Otros','•','GASTO']}
const activeMoves=()=>S.user==='AMBOS'?S.moves:S.moves.filter(x=>x.persona===S.user);
function sum(type){return activeMoves().filter(x=>x.tipo===type).reduce((a,x)=>a+x.monto,0)}function icon(n){return n}
async function load(){try{const r=await getDocs(query(collection(db,'movimientos'),where('mes','==',S.month)));S.moves=r.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>b.fechaLocal.localeCompare(a.fechaLocal));const b=await getDoc(doc(db,'presupuestos',S.month));S.budget=b.exists()?b.data():null;if(!document.querySelector('.sheet-bg'))render()}catch(e){console.error(e);toast('No pudimos conectar con Firestore.');if(!document.querySelector('.sheet-bg'))render()}}
function shell(content){let theme=S.user==='PIERO'?'piero':S.user==='MAFER'?'mafer':'ambos',label=S.user==='PIERO'?'Vista personal de Piero':S.user==='MAFER'?'Vista personal de Mafer':'Vista compartida';return `<main class="shell ${theme}"><header class="brand"><span class="wing">◒◓</span><div><b>Piero & Mafer</b><small>${label} · ${VERSION}</small></div></header><div class="view">${content}</div></main><nav class="nav ${theme}">${[['home','⌂','Inicio'],['calendar','▦','Calendario'],['add','＋','Agregar'],['stats','◔','Estadísticas'],['more','☰','Más']].map(([r,i,t])=>`<button class="${S.route===r?'active':''} ${r==='add'?'add':''}" data-route="${r}" aria-label="${t}">${i}<span>${r==='add'?'':t}</span></button>`).join('')}</nav>`}
function month(){return `<div class="month"><button data-month="-1" aria-label="Mes anterior">‹</button><b>${monthName()}</b><button data-month="1" aria-label="Mes siguiente">›</button><button data-month="0">Hoy</button></div>`}
function item(m){const c=cat(m.categoriaId);return `<button class="item" data-edit="${m.id}"><span class="ico">${c[2]}</span><span class="copy"><b>${m.descripcion||c[1]}</b><small>${m.persona} · ${m.fechaLocal}</small></span><b class="${m.tipo==='INGRESO'?'income':''}">${m.tipo==='INGRESO'?'+':'−'}${money(m.monto)}</b></button>`}
function home(){const ms=activeMoves(),g=sum('GASTO'),i=sum('INGRESO'),limit=S.budget?.limiteGeneral||0,p=limit?Math.min(100,g/limit*100):0;const by={};ms.filter(x=>x.tipo==='GASTO').forEach(x=>by[x.categoriaId]=(by[x.categoriaId]||0)+x.monto);return `${month()}<section class="card balance"><span>Balance del mes</span><h1>${money(i-g)}</h1><div class="row"><p>Ingresos<b>${money(i)}</b></p><p>Gastos<b>${money(g)}</b></p></div></section><div class="grid"><section class="card"><span>Movimientos</span><b>${ms.length}</b></section><section class="card"><span>Promedio diario</span><b>${money(g/new Date().getDate())}</b></section></div><section class="card budget"><div class="row"><b>Presupuesto</b><small>${limit?money(limit):'Sin definir'}</small></div><div class="progress"><i style="width:${p}%"></i></div><small class="muted">${limit?`${Math.round(p)}% usado · ${money(limit-g)} disponible`:'Defínelo en Más'}</small></section><div class="section-title"><h2>${S.user==='AMBOS'?'Nuestros gastos':`Gastos de ${S.user==='PIERO'?'Piero':'Mafer'}`}</h2><button data-route="history">Ver todos</button></div><div class="list">${ms.length?ms.slice(0,5).map(item).join(''):'<p class="empty">Aún no hay movimientos en esta vista.</p>'}</div>`}
function calendar(){const ms=activeMoves();let[y,m]=S.month.split('-').map(Number),off=(new Date(y,m-1,1).getDay()+6)%7,days=new Date(y,m,0).getDate(),by={};ms.forEach(x=>(by[x.fechaLocal]??=[]).push(x));let cells=Array.from({length:off+days},(_,n)=>{if(n<off)return'<span></span>';let d=n-off+1,k=`${S.month}-${pad(d)}`,g=(by[k]||[]).filter(x=>x.tipo==='GASTO').reduce((a,x)=>a+x.monto,0);return `<button class="day ${g?'has':''}" data-day="${k}"><b>${d}</b>${g?`<small>${money(g)}</small>`:''}</button>`}).join('');return `${month()}<div class="week"><span>L</span><span>M</span><span>M</span><span>J</span><span>V</span><span>S</span><span>D</span></div><div class="calendar">${cells}</div><div id="daybox" class="list" style="margin-top:18px"><p class="empty">Selecciona un día.</p></div>`}
function history(){const ms=activeMoves();return `<h1>Historial</h1><input id="search" class="search" placeholder="Buscar movimiento..."><div class="filters"><select id="type"><option value="">Todos los tipos</option><option>GASTO</option><option>INGRESO</option></select><select id="person"><option value="">${S.user==='AMBOS'?'Todas las personas':S.user}</option>${S.user==='AMBOS'?'<option>PIERO</option><option>MAFER</option><option>AMBOS</option>':''}</select></div><div id="history" class="list">${ms.map(item).join('')||'<p class="empty">No hay movimientos.</p>'}</div>`}
function stats(){const ms=activeMoves();let g=sum('GASTO'),by={};ms.filter(x=>x.tipo==='GASTO').forEach(x=>by[x.categoriaId]=(by[x.categoriaId]||0)+x.monto);const sorted=Object.entries(by).sort((a,b)=>b[1]-a[1]),top=sorted.slice(0,3),a=top[0]?(top[0][1]/g*100):0,b=top[1]?(top[1][1]/g*100):0,c=top[2]?(top[2][1]/g*100):0,ring=`conic-gradient(#38bdf8 0 ${a}%,#0f172a ${a}% ${a+b}%,#fda4af ${a+b}% ${a+b+c}%,#dff5ff ${a+b+c}% 100%)`;return `<h1>Estadísticas</h1>${month()}<section class="card stat"><div style="display:flex;align-items:center;gap:18px"><div style="width:112px;height:112px;flex:none;border-radius:50%;background:${ring};display:grid;place-items:center"><span style="width:76px;height:76px;border-radius:50%;background:var(--card);display:grid;place-items:center;text-align:center;font-size:.75rem;font-weight:800">${money(g)}<small style="display:block;color:var(--muted);font-weight:500">gastado</small></span></div><div><h2>Resumen del mes</h2><p style="margin:4px 0">${ms.length} movimientos registrados</p><p style="margin:4px 0">Promedio: <b>${money(g/new Date().getDate())}</b> por día</p></div></div></section><section class="card stat"><h2>Gastos por categoría</h2>${sorted.map(([id,n])=>`<p>${cat(id)[2]} ${cat(id)[1]} <b>${money(n)} · ${Math.round(n/g*100)}%</b></p><div class="bar"><i style="width:${g?n/g*100:0}%"></i></div>`).join('')||'<p class="empty">Necesitamos algunos movimientos.</p>'}</section><section class="card stat"><h2>Distribución de gastos</h2><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:7px">${['PIERO','MAFER','AMBOS'].map(p=>{let n=ms.filter(x=>x.tipo==='GASTO'&&x.persona===p).reduce((x,m)=>x+m.monto,0);return `<div style="padding:10px 6px;border-radius:13px;background:var(--ice);text-align:center"><small>${p}</small><b style="display:block;margin-top:4px;font-size:.78rem">${money(n)}</b><small>${g?Math.round(n/g*100):0}%</small></div>`}).join('')}</div></section>`}
function more(){return `<h1>Más</h1><div class="list"><button class="item" data-route="budget"><span class="copy"><b>Presupuesto</b><small>General y mensual</small></span>›</button><button class="item" data-route="history"><span class="copy"><b>Historial</b><small>Buscar y filtrar</small></span>›</button><button class="item" data-action="switch"><span class="copy"><b>Cambiar vista</b><small>Piero / Mafer</small></span>›</button></div>`}
function budget(){return `<h1>Presupuesto</h1>${month()}<form id="budgetform" class="card stat"><label class="field">Límite general mensual<input required name="limit" inputmode="decimal" type="number" min="0" step="0.01" value="${S.budget?.limiteGeneral||''}" placeholder="S/ 0.00"></label><button class="save">Guardar presupuesto</button></form>`}
function render(){document.body.className=S.user==='PIERO'?'theme-piero':S.user==='MAFER'?'theme-mafer':S.user==='AMBOS'?'theme-ambos':'theme-login';if(!S.user){$('#app').innerHTML=`<section class="login"><article class="card"><span class="wing">◒◓</span><h1>Nuestro Dinero</h1><p class="muted">Elige la vista de nuestro mes.</p><div class="personas personas-three"><button data-user="PIERO">Piero<br><small>Vista personal</small></button><button data-user="AMBOS">Ambos<br><small>Vista compartida</small></button><button data-user="MAFER">Mafer<br><small>Vista personal</small></button></div></article></section>`;return}let v={home,calendar,history,stats,more,budget}[S.route]||home;$('#app').innerHTML=shell(v())}
function form(m={}){m=m||{};let type=m.tipo||'GASTO';return `<div class="sheet-bg" data-close><section class="sheet" onclick="event.stopPropagation()"><div class="handle"></div><div class="sheet-head"><h2>${m.id?'Editar':'Agregar'} movimiento</h2><button data-close aria-label="Cerrar">×</button></div><form id="moveform"><input type="hidden" name="id" value="${m.id||''}"><input type="hidden" name="tipo" value="${type}"><input type="hidden" name="persona" value="${m.persona||S.user}"><input type="hidden" name="metodoPago" value="${m.metodoPago||'YAPE'}"><div class="chips" id="types"><button type="button" class="${type==='GASTO'?'on':''}" data-type="GASTO">Gasto</button><button type="button" class="${type==='INGRESO'?'on':''}" data-type="INGRESO">Ingreso</button></div><label class="field amount">Monto<input required name="monto" inputmode="decimal" type="number" min="0.01" step="0.01" value="${m.monto||''}" placeholder="S/ 0.00"></label><label class="field">Categoría<select required name="categoriaId">${cats.filter(c=>c[3]===type).map(c=>`<option value="${c[0]}" ${c[0]===m.categoriaId?'selected':''}>${c[1]}</option>`).join('')}</select></label><label class="field">Persona<div class="chips">${['PIERO','MAFER','AMBOS'].map(p=>`<button type="button" data-person="${p}" class="${(m.persona||S.user)===p?'on':''}">${p[0]+p.slice(1).toLowerCase()}</button>`).join('')}</div></label><label class="field">Fecha<input required type="date" name="fechaLocal" value="${m.fechaLocal||today()}"></label><label class="field">Método de pago<div class="chips">${methods.map(p=>`<button type="button" data-pay="${p}" class="${(m.metodoPago||'YAPE')===p?'on':''}">${p[0]+p.slice(1).toLowerCase()}</button>`).join('')}</div></label><label class="field">Descripción<input name="descripcion" value="${m.descripcion||''}" placeholder="Cena en restaurante"></label><button class="save">Guardar movimiento</button></form>${m.id?'<button class="delete" data-delete>Eliminar movimiento</button>':''}</section></div>`}
// Close only from the explicit × control; interactions inside the sheet must remain open.
document.addEventListener('click',e=>{if(e.target.hasAttribute('data-close'))$('.sheet-bg')?.remove()},true);
document.head.insertAdjacentHTML('beforeend',`<style>
body.theme-piero{background:#e8eef9}body.theme-mafer{background:#eaf8ff}body.theme-login{background:#edf7ff}
.theme-piero .card{background:#f8faff;border-color:#cdddf5}.theme-mafer .card{background:#fcfeff;border-color:#cbeefe}
.theme-piero.nav{background:#edf3fd}.theme-mafer.nav{background:#f0fbff}.theme-piero.nav .add{background:#0f172a}.theme-mafer.nav .add{background:#0284c7}
.theme-piero .brand b,.theme-piero .balance h1{color:#0b1d3d}.theme-mafer .brand b,.theme-mafer .balance h1{color:#075985}
#movement-preview{display:block;margin:4px 0 8px;color:#0369a1;font-size:.8rem;font-weight:700}
</style>`);
document.head.insertAdjacentHTML('beforeend',`<style>
body.theme-piero{background:#090f1d!important;color:#f7fbff!important}
body.theme-piero .shell{color:#f7fbff!important}
body.theme-piero .card,body.theme-piero .list{background:linear-gradient(145deg,#101b30,#172742)!important;border-color:#334b6d!important}
body.theme-piero .month{background:#111d33!important;border-color:#3b5274!important;color:#fff!important}
body.theme-piero .month b{color:#fff!important}
body.theme-piero .balance:after{border-color:#fb718544!important}
body.theme-piero .nav{background:#0a1322f5!important;border-color:#304664!important}
body.theme-piero .grid .card,body.theme-piero .budget{background:linear-gradient(145deg,#111d32,#1a2b47)!important}
body.theme-piero .progress,body.theme-piero .bar{background:#314765!important}
body.theme-piero .progress i,body.theme-piero .bar i{background:linear-gradient(90deg,#fb7185,#fda4af)!important}
body.theme-piero .card *,body.theme-piero .list .item{color:#f5f9ff!important}
body.theme-piero .card small,body.theme-piero .list .item small,body.theme-piero .muted{color:#c4d3e7!important}
body.theme-piero .ico{background:#263a5a!important;color:#fda4af!important}
body.theme-piero .section-title button,body.theme-piero .month button{color:#fda4af!important}
body.theme-piero .nav .active{color:#fda4af!important}
body.theme-piero .nav .add{background:#090f1d!important;border:1px solid #fb7185!important;color:#fda4af!important}
body.theme-piero .shell,body.theme-piero .nav{color:#f8fbff}
body.theme-piero .brand b,body.theme-piero h1,body.theme-piero h2,body.theme-piero h3,body.theme-piero .month b,body.theme-piero .stat p b{color:#fff!important}
body.theme-piero .brand small,body.theme-piero .muted,body.theme-piero .copy small,body.theme-piero .stat p,body.theme-piero .budget small{color:#cbd9eb!important}
body.theme-piero .item,body.theme-piero .grid b,body.theme-piero .balance p b{color:#f1f6ff!important}
body.theme-piero .section-title button,body.theme-piero .month button{color:#fda4af!important}
body.theme-piero .chips .on,body.theme-piero .save{color:#fff!important;text-shadow:0 1px 1px #6b1027}
</style>`);
document.head.insertAdjacentHTML('beforeend',`<style>
body.theme-piero{--card:#172742;--ice:#263a5a}
body.theme-piero .stat [style*="background:var(--ice)"],body.theme-piero .stat span[style*="background:var(--card)"]{background:#223756!important;border:1px solid #3d587e;color:#f8fbff!important}
body.theme-piero .stat [style*="background:var(--ice)"] small,body.theme-piero .stat span small{color:#cbd9eb!important}
body.theme-piero .stat h2,body.theme-piero .stat b{color:#fff!important}
.personas-three{grid-template-columns:repeat(3,1fr)!important}.personas-three button{min-width:0;padding:14px 4px;font-size:.84rem}.personas-three button:nth-child(2){background:linear-gradient(145deg,#0f172a,#0284c7);color:#fff;border-color:#38bdf8}
body.theme-ambos{background:radial-gradient(circle at 15% 0,#d9f6ff 0,transparent 29%),radial-gradient(circle at 90% 100%,#ffe3ea 0,transparent 31%),#f4fbff}.theme-ambos .nav{background:#f8fdffed}.theme-ambos .nav .add{background:linear-gradient(145deg,#0f172a,#0284c7);border:1px solid #7dd3fc}.theme-ambos .card{background:linear-gradient(145deg,#fff,#f1faff)}
</style>`);
setTimeout(()=>document.addEventListener('input',e=>{if(e.target.id!=='search'&&e.target.id!=='type'&&e.target.id!=='person')return;const list=$('#history');if(!list)return;let q=$('#search').value.toLowerCase(),t=$('#type').value,p=$('#person').value;list.innerHTML=activeMoves().filter(x=>(!q||(x.descripcion||'').toLowerCase().includes(q))&&(!t||x.tipo===t)&&(!p||x.persona===p)).map(item).join('')||'<p class="empty">Sin resultados.</p>'}),0);
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
async function saveMovementForm(form){
  if(!form.reportValidity())return;
  const d=Object.fromEntries(new FormData(form));
  if(!(Number(d.monto)>0)){toast('Ingresa un monto mayor a cero.');return}
  const button=form.querySelector('.save');button.disabled=true;button.textContent='Guardando…';
  try{
    const data={...d,monto:Number(d.monto),mes:d.fechaLocal.slice(0,7),anio:Number(d.fechaLocal.slice(0,4)),fecha:Timestamp.fromDate(new Date(`${d.fechaLocal}T12:00:00`)),updatedAt:serverTimestamp()};
    if(d.id)await updateDoc(doc(db,'movimientos',d.id),data);
    else await addDoc(collection(db,'movimientos'),{...data,createdAt:serverTimestamp()});
    $('.sheet-bg')?.remove();S.month=data.mes;toast('Movimiento guardado ✓');await load();
  }catch(error){console.error(error);button.disabled=false;button.textContent='Guardar movimiento';toast('No pudimos guardar. Revisa Firestore o el bloqueador del navegador.')}
}
const movementFormObserver=new MutationObserver(()=>{const form=$('#moveform');if(!form||form.dataset.bound)return;form.dataset.bound='true';form.addEventListener('submit',event=>{event.preventDefault();event.stopPropagation();saveMovementForm(form)})});
movementFormObserver.observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.user){S.user=b.dataset.user;localStorage.ndUser=S.user;render();load();return}if(b.dataset.route){S.route=b.dataset.route;render();if(S.route==='add'){$('#app').insertAdjacentHTML('beforeend',form());S.route='home'}return}if(b.dataset.month!==undefined){if(b.dataset.month==='0'){S.month=ym();load()}else moveMonth(+b.dataset.month);return}if(b.dataset.edit){$('#app').insertAdjacentHTML('beforeend',form(S.moves.find(x=>x.id===b.dataset.edit)));return}if(b.dataset.day){let ms=activeMoves().filter(x=>x.fechaLocal===b.dataset.day);$('#daybox').innerHTML=ms.map(item).join('')||'<p class="empty">No hay movimientos este día.</p>';return}if(b.dataset.action==='switch'){localStorage.removeItem('ndUser');S.user='';render();return}if(b.hasAttribute('data-close')||e.target.hasAttribute('data-close')){$('.sheet-bg')?.remove();return}if(b.dataset.type){$('[name=tipo]').value=b.dataset.type;$('#types').querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));let select=$('[name=categoriaId]');select.innerHTML=cats.filter(c=>c[3]===b.dataset.type).map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}if(b.dataset.person){$('[name=persona]').value=b.dataset.person;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b))}if(b.dataset.pay){$('[name=metodoPago]').value=b.dataset.pay;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b))}if(b.hasAttribute('data-delete')){if(confirm('¿Eliminar este movimiento?')){await deleteDoc(doc(db,'movimientos',$('[name=id]').value));$('.sheet-bg').remove();toast('Movimiento eliminado');load()}}});
document.addEventListener('submit',async e=>{e.preventDefault();let f=e.target,d=Object.fromEntries(new FormData(f));try{if(f.id==='budgetform'){await setDoc(doc(db,'presupuestos',S.month),{mes:S.month,limiteGeneral:+d.limit,updatedAt:serverTimestamp()});toast('Presupuesto guardado');load();return}if(f.id==='moveform'){let data={...d,monto:+d.monto,mes:d.fechaLocal.slice(0,7),anio:+d.fechaLocal.slice(0,4),fecha:Timestamp.fromDate(new Date(d.fechaLocal+'T12:00:00')),updatedAt:serverTimestamp()};if(d.id)await updateDoc(doc(db,'movimientos',d.id),data);else await addDoc(collection(db,'movimientos'),{...data,createdAt:serverTimestamp()});$('.sheet-bg').remove();toast('Movimiento guardado ✓');S.month=data.mes;load()}}catch(err){console.error(err);toast('No pudimos guardar. Revisa las Rules.')}});
document.addEventListener('input',e=>{if(e.target.name==='monto'){let preview=$('#movement-preview');if(!preview){e.target.insertAdjacentHTML('afterend','<small id="movement-preview">Monto a registrar: S/ 0.00</small>');preview=$('#movement-preview')}preview.textContent=`Monto a registrar: ${money(e.target.value)}`}if(e.target.id==='search'||e.target.id==='type'||e.target.id==='person'){let q=$('#search').value.toLowerCase(),t=$('#type').value,p=$('#person').value;$('#history').innerHTML=S.moves.filter(x=>(!q||(x.descripcion||'').toLowerCase().includes(q))&&(!t||x.tipo===t)&&(!p||x.persona===p)).map(item).join('')||'<p class="empty">Sin resultados.</p>'}});document.addEventListener('click',e=>{if(e.target.classList.contains('sheet-bg'))e.target.remove();let b=e.target.closest('[data-type],[data-person],[data-pay]');if(!b)return;if(b.dataset.type){$('[name=tipo]').value=b.dataset.type;$('#types').querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));$('[name=categoriaId]').innerHTML=cats.filter(c=>c[3]===b.dataset.type).map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}if(b.dataset.person){$('[name=persona]').value=b.dataset.person;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b))}if(b.dataset.pay){$('[name=metodoPago]').value=b.dataset.pay;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b))}},true);document.head.insertAdjacentHTML('beforeend','<style>.piero{--sky:#1d4ed8;--blue:#0f172a;--ice:#eaf1ff;--line:#dbeafe}.piero .balance{background:linear-gradient(145deg,#fff,#eaf1ff)}.piero .wing{color:#0f172a}.piero.nav .add{background:#0f172a}</style>');render();if(S.user)load();

